FILE_UPDATE_HOSTS="_update_hosts.sh"
FILE_HOSTNAME="/etc/hostname"
FILE_HOSTS="/etc/hosts"
id="pi"
pword="raspberry"
localhostsfile="hosts.local"
localhostnamefile="hostname.local"

download_location="https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/"
containerd="containerd.io_1.2.6-3_armhf.deb"
docker_ce_cli="docker-ce-cli_18.09.7~3-0~debian-buster_armhf.deb"
docker_ce="docker-ce_18.09.7~3-0~debian-buster_armhf.deb"