machine_locale: en_US.UTF-8
new_keyboard: us
time_zone: America/Chicago

std_username: marknic
std_password: raspberry
config_group: kubconfig

k8s_version: 1.19.1

redis_ip: 192.168.1.97
redis_hostname: redisserver