---
- name: install kubernetes on all machines
  hosts: all
  vars_files:
    - vars/default.yml
  any_errors_fatal: true
  become: true

  tasks:

  - name: Configure iptables
    template:
      src: "templates/etc/docker/k8s.conf.j2"
      dest: "/etc/sysctl.d/k8s.conf"
      owner: "root"
      group: "root"
      mode: "0644"

  - name: finish updating iptables
    shell: sysctl --system

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  - name: Update apt-get repo and cache
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600

  - name: install kubelet
    apt:
      name: kubelet
      state: present

  - name: install kubeadm
    apt:
      name: kubeadm
      state: present

  - name: install kubectl
    apt:
      name: kubectl
      state: present

  - name: mark hold kubelet kubeadm kubectl
    shell: apt-mark hold kubelet kubeadm kubectl

