---
- hosts: master
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
  - name: Update all packages to the latest version...
    apt:
      upgrade: dist
    become: true

  - name: Enabling net.bridge.bridge-nf-call-iptables...
    sysctl:
      name: "{{ item }}"
      value: "1"
      sysctl_file: /etc/sysctl.conf
      reload: yes
    with_items:
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward

  - name: initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address="{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"  >> cluster_initialized.txt
    args:
      chdir: /home/{{ std_username }}
      creates: cluster_initialized.txt
    become: true

  - name: create .kube directory
    become: true
    become_user: "{{ std_username }}"
    file:
      path: /home/{{ std_username }}/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/{{ std_username }}/.kube/config
      remote_src: yes
      owner: "{{ std_username }}"

  - name: install Pod network
    become: true
    become_user: "{{ std_username }}"
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
    args:
      chdir: /home/{{ std_username }}
      creates: pod_network_setup.txt