---
- name: host file update - Local DNS setup across all the servers
  hosts: localhost
  vars_files:
    - vars/default.yml
  any_errors_fatal: true
  become: true

  tasks:

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      path: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
    delegate_to: localhost

  - name: add an entry for the resis server
    lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ redis_ip }}  {{ redis_hostname }}"
    delegate_to: localhost
