machine_locale: en_US.UTF-8
new_keyboard: us
time_zone: America/Chicago

std_username: marknic
std_password: raspberry
config_group: kubconfig

# docker__users:
#   - "{{ ansible_env.SUDO_USER | d('root') }}"
#   - "{{ std_username }}"

redis_ip: 192.168.1.97
redis_hostname: redisserver
