---
- name: install containerd
  hosts: all
  vars_files:
    - vars/default.yml
  become: true

  tasks:
  - name: Install containerd - All
    apt:
      name: containerd
      state: latest
      update_cache: true

  - name: Update apt-get repo and cache
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600

  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      force_apt_get: true

  - name: ansible create directory with mode setting example
    file:
      path: /etc/containerd
      state: directory
      mode: "u=rw,g=rw,o=rw"

  - name: create config.toml
    shell: containerd config default > /home/ubuntu/config.toml

  - name: move the config file to the config folder
    command: mv /home/ubuntu/config.toml /etc/containerd/config.toml
