---
- name: install kubernetes on all machines
  hosts: all
  vars_files:
    - vars/default.yml
  become: true

  tasks:
  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  - name: install kubeadm
    apt:
      name: kubeadm
      state: present

  - name: install kubelet
    apt:
      name: kubelet
      state: present

  - name: install kubectl
    apt:
      name: kubectl
      state: present


  - name: remove CR/LF
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '[\n\r]'
      replace: ''

  - name: remove 1
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '(cgroup_\S*|swapaccount\S*)'
      replace: ''

  - name: remove 2
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '\s{2,}'
      replace: ''

  - name: Add cgroup settings
    lineinfile:
      path: /boot/firmware/cmdline.txt
      state: present
      insertafter: "^.*$"
      line: ' cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'

  - name: remove CR/LF
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '[\n\r]'
      replace: ''


  - name: Unconditionally reboot the machine with all defaults
    reboot:
