---
- name: configure the k8s cluster
  hosts: master
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
  - name: pull the container images needed for Kubernetes
    shell: kubeadm config images pull

  - name: create the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16


